version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: nave3/base-conversion:1.0.0
    container_name: base-conversion
    volumes:
      - .:/usr/app
    tty: true